# Provide a custom message
message: ""

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""

service:
  type: LoadBalancer
  port: 80

deployment:
  replicaCount: 1
  container:
    image:
      repository: "isurabuy/user-manager-pro-app"
      tag: '1658821330'
      pullPolicy: IfNotPresent
    port: 80

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}

